name: Update Index and Logs

on:
  push:
    branches:
      - main

jobs:
  update_index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate Index and Logs
        run: |
          echo "<html><head><style>body {font-family: 'Arial', sans-serif;} h1 {color: #333;} ul {list-style: none; padding: 0;} li {margin-bottom: 8px;} a {text-decoration: none; color: #0366d6;} a:hover {text-decoration: underline;}</style></head><body><h1>Project Index</h1><ul>" > index.html
          find . -maxdepth 1 -type d ! -path . ! -name ".git" ! -name ".github" | sed 's|^./||' | awk '{print "<li><a href=\""$1"\">"$1"</a></li>"}' >> index.html
          echo "</ul></body></html>" >> index.html
          echo "Generated index.html at $(date)" > update.log

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add index.html update.log
          git commit -m "Update project index and logs [skip ci]"
          git push
