name: Update Index and Logs

on:
  push:
    branches:
      - main

jobs:
  update_index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate Index and Logs
        run: |
          echo "<html><head><style>body {font-family: 'Arial', sans-serif; background-color: #f5f5f5; margin: 0; padding: 0;} h1 {color: #333; text-align: center; padding: 20px 0; background-color: #0366d6; margin: 0; color: #fff;} ul {list-style: none; padding: 0; margin: 20px; background-color: #fff; border-radius: 10px; box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);} li {margin: 0; padding: 10px; border-bottom: 1px solid #eee;} a {text-decoration: none; color: #0366d6; font-weight: bold;} a:hover {text-decoration: underline;}</style></head><body><h1>Project Index</h1><ul>" > index.html
          find . -maxdepth 1 -type d ! -path . ! -name ".git" ! -name ".github" | sed 's|^./||' | awk '{print "<li><a href=\""$1"\">"$1"</a></li>"}' >> index.html
          echo "</ul></body></html>" >> index.html
          echo "Generated index.html at $(date)" > update.log

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add index.html update.log
          git commit -m "Update project index and logs [skip ci]"
          git push
